# Generated by Django 2.2 on 2019-04-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0004_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
