# Generated by Django 2.2 on 2019-04-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='groupID',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='groupID',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='groupName',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='publicKey',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='sessionKey',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='groupID',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='groupName',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='publicKey',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='publicKey',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
