# Generated by Django 2.2 on 2019-04-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0006_auto_20190407_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicKey', models.CharField(max_length=3000)),
                ('groupID', models.CharField(max_length=500)),
                ('groupName', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='publicKey',
        ),
        migrations.AlterField(
            model_name='group',
            name='groupID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
