# Generated by Django 2.2 on 2019-04-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0007_auto_20190407_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('fileName', models.CharField(max_length=3000)),
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('groupId', models.IntegerField()),
            ],
        ),
    ]
