# Generated by Django 2.2 on 2019-04-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0008_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='id',
        ),
        migrations.AddField(
            model_name='request',
            name='requestId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
